#mySQL
mySQL_DATASOURCE_URL: "jdbc:mysql://localhost:3306/mySQLDB"
mySQL_DATASOURCE_USER: dbuser
mySQL_DATASOURCE_PASSWORD: dbpass

spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: ${mySQL_DATASOURCE_URL}
      username: ${mySQL_DATASOURCE_USER}
      password: ${mySQL_DATASOURCE_PASSWORD}
      createDatabaseIfNotExist: true
      useUnicode: yes
      characterEncoding: UTF-8
      initialization-mode: never
   jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      datasource:
         auto-commit: false
         hikari:
            auto-commit: false
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
            generate_statistics: true
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp